openapi: 3.0.3
info:
  description: "Famifarm API specification"
  version: "1.0.0"
  title: "Famifarm-API"
  
paths:
  /events:
    get:
      summary: List all events
      operationId: listEvents
      tags:
        - events
      parameters:
        - name: maxResult
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of events
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Event"
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    LocalizedEntry: 
       type: array
       items:
         $ref: '#/components/schemas/LocalizedValue'
  
    LocalizedValue: 
      type: object
      required:
        - language
        - value
      properties:
        language:
          type: string
          minLength: 2
          maxLength: 2        
        value:
          type: string
          
    Team:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          $ref: '#/components/schemas/LocalizedEntry'

  
    WastageReason:
      description: "Reason why a product has been thrown away"
      properties:
        id:
          type: "string"
          format: "uuid"
        reason:
          $ref: '#/components/schemas/LocalizedEntry'
  
    PerformedCultivationAction:
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          $ref: '#/components/schemas/LocalizedEntry'
          
    PackageSize:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          type: "string"
  
    Product:
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          $ref: '#/components/schemas/LocalizedEntry'
        defaultPackageSize:
          type: "string"
          format: "uuid"
    
    Seed:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        name:
          $ref: '#/components/schemas/LocalizedEntry'      
          
    SeedBatch:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        code:
          description: "Manufacturer's code for the batch"        
          type: "string"
        seedId:
          type: "string"
          format: "uuid"
        time:
          description: "Time when the seed has arrived"
          type: "string"
          format: "datetime"
          
    ProductionLine:
      properties:
        id:
          type: "string"
          format: "uuid"
        lineNumber:
          type: "integer"
          format: "int32"    
          
    CellType:
      type: "string"
      enum:
        - SMALL
        - LARGE   
        
    Batch:
      description: Identifies a single batch for it's entire life-cycle 
      type: "object"
      required:
        - productId
      properties:
        id:
          type: "string"
          format: "uuid"
        productId:
          type: "string"
          format: "uuid"
        
    Event:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        batchId:
          type: "string"
          format: "uuid"
        userId:
          description: "Id of user who added this entry"
          type: "string"
          format: "uuid"
        time:
          description: "Time when the entry was added"
          type: "string"
          format: "datetime"
        data:
          oneOf:
            - $ref: '#/components/schemas/PlantingEventData'
            - $ref: '#/components/schemas/SowingEventData'
            - $ref: '#/components/schemas/PackingEventData'
            - $ref: '#/components/schemas/TableSpreadEventData'
            - $ref: '#/components/schemas/CultivationObservationEventData'
            - $ref: '#/components/schemas/HarvestEventData'
            - $ref: '#/components/schemas/WastageEventData'
            
    PlantingEventData:
      properties:
        productionLineId:
          description: "Production line id"
          type: "string"
          format: "uuid"
        gutterNumber:
          type: "integer"
          format: "int32"
        gutterCount:
          description: "How many gutter were used during the planting"
          type: "integer"
          format: "int32"
        trayCount:
          description: "How many trays were planted"
          type: "integer"
          format: "int32"
        workerCount:
          description: "How many workers were doing the planting"
          type: "integer"
          format: "int32"
        workDuration:
          description: Duration of work in minutes
          type: "integer"
          format: "int32"
          
    SowingEventData:
      description: "Entry when a batch has been sowed"
      type: "object"
      required: 
        - productionLineId
        - cellType
        - amount
      properties:
        productionLineId:
          type: "string"
          format: "uuid"
        gutterNumber:
          type: "integer"
          format: "int32"
        seedBatchId:
          type: "string"
          format: "uuid"
        cellType:
          $ref: "#/components/schemas/CellType"
        amount:
          type: "number"
          format: "double"
          
    TableSpreadEventData:
      description: Event of spreading the young plant trays to nursery tables
      properties:
        tableCount:
          description: "Count of tables used"
          type: "integer"
          format: "int32"
        location:
          description: "Where the batch has been placed"
          type: "string"

    PackingEventData:
      properties:
        packedAmount:
          description: "Amount of packed items"
          type: "integer"
          format: "int32"
        packageSize:
          type: "string"
          format: "uuid"
          
    CultivationObservationEventData:
      properties:
        weight:
          description: "Weight in grams"
          type: "number"
          format: "double"
        pests:
          description: "Possible pest observations"
          type: "string"        
        luminance:
          description: "Luminance in lumens on the time of observation"
          type: "number"
          format: "double"
        performedActionIds:
          description: "List of ids of cultivation actions done based on observations"
          type: "array"
          items:
            type: "string"
            format: "uuid"
            
    HarvestEventData:
      properties:
        teamId:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          enum:
            - BAGGING
            - CUTTING
            - BOXING
        productionLineId:
          description: "Production line id"
          type: "string"
          format: "uuid"
            
    WastageEventData:
      description: "Entry of products has been thrown away"
      properties:
        reasonId:
          description: "Id of reason a product has been thrown away"
          type: "string"
          format: "uuid"
        amount:
          type: "integer"
          format: "int32"
          
    Error:
      type: object
      required: [message]
      properties:
        message:
          description: The error message
          type: string