/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchPhase } from './batchPhase';


/**
 * Identifies a single batch for it's entire life-cycle
 */
export interface Batch { 
    id?: string;
    productId: string;
    /**
     * Read-only field that shows line numbers used in sowing phase
     */
    readonly sowingLineNumbers?: Array<string>;
    phase?: BatchPhase;
    createdAt?: string;
}
export interface BatchOpt { 
    id?: string;
    productId?: string;
    /**
     * Read-only field that shows line numbers used in sowing phase
     */
    readonly sowingLineNumbers?: Array<string>;
    phase?: BatchPhase;
    createdAt?: string;
}
