/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type BatchPhase = 'SOWING' | 'PLANTING' | 'TABLE_SPREAD' | 'HARVEST' | 'PACKING' | 'COMPLETE';

export const BatchPhase = {
    SOWING: 'SOWING' as BatchPhase,
    PLANTING: 'PLANTING' as BatchPhase,
    TABLESPREAD: 'TABLE_SPREAD' as BatchPhase,
    HARVEST: 'HARVEST' as BatchPhase,
    PACKING: 'PACKING' as BatchPhase,
    COMPLETE: 'COMPLETE' as BatchPhase
};
