/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CultivationObservationEventData { 
    /**
     * Weight in grams
     */
    weight?: number;
    /**
     * Possible pest observations
     */
    pests?: string;
    /**
     * Luminance in lumens on the time of observation
     */
    luminance?: number;
    /**
     * List of ids of cultivation actions done based on observations
     */
    performedActionIds?: Array<string>;
}
export interface CultivationObservationEventDataOpt { 
    /**
     * Weight in grams
     */
    weight?: number;
    /**
     * Possible pest observations
     */
    pests?: string;
    /**
     * Luminance in lumens on the time of observation
     */
    luminance?: number;
    /**
     * List of ids of cultivation actions done based on observations
     */
    performedActionIds?: Array<string>;
}
