/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CutPacking { 
    id?: string;
    weight: number;
    productId: string;
    productionLineId: string;
    cuttingDay: string;
    sowingDay: string;
    producer: string;
    contactInformation: string;
    gutterCount: number;
    gutterHoleCount: number;
    storageCondition: string;
}
export interface CutPackingOpt { 
    id?: string;
    weight?: number;
    productId?: string;
    productionLineId?: string;
    cuttingDay?: string;
    sowingDay?: string;
    producer?: string;
    contactInformation?: string;
    gutterCount?: number;
    gutterHoleCount?: number;
    storageCondition?: string;
}
