/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventType } from './eventType';
import { CultivationObservationEventData } from './cultivationObservationEventData';
import { HarvestEventData } from './harvestEventData';
import { PackingEventData } from './packingEventData';
import { PlantingEventData } from './plantingEventData';
import { SowingEventData } from './sowingEventData';
import { TableSpreadEventData } from './tableSpreadEventData';
import { WastageEventData } from './wastageEventData';


export interface Event { 
    id?: string;
    productId: string;
    /**
     * Id of user who added this entry
     */
    userId?: string;
    /**
     * Time when the entry was added
     */
    startTime?: string;
    /**
     * Time when the entry was added
     */
    endTime?: string;
    additionalInformation?: string;
    type: EventType;
    data: CultivationObservationEventData | HarvestEventData | PackingEventData | PlantingEventData | SowingEventData | TableSpreadEventData | WastageEventData;
}
export interface EventOpt { 
    id?: string;
    productId?: string;
    /**
     * Id of user who added this entry
     */
    userId?: string;
    /**
     * Time when the entry was added
     */
    startTime?: string;
    /**
     * Time when the entry was added
     */
    endTime?: string;
    additionalInformation?: string;
    type?: EventType;
    data?: CultivationObservationEventData | HarvestEventData | PackingEventData | PlantingEventData | SowingEventData | TableSpreadEventData | WastageEventData;
}
