/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CultivationObservationEventData } from './cultivationObservationEventData';
import { HarvestEventData } from './harvestEventData';
import { PackingEventData } from './packingEventData';
import { PlantingEventData } from './plantingEventData';
import { SowingEventData } from './sowingEventData';
import { TableSpreadEventData } from './tableSpreadEventData';
import { WastageEventData } from './wastageEventData';


export interface Event { 
    id?: string;
    batchId: string;
    /**
     * Id of user who added this entry
     */
    userId?: string;
    /**
     * Time when the entry was added
     */
    startTime?: string;
    /**
     * Time when the entry was added
     */
    endTime?: string;
    type: Event.TypeEnum;
    data: CultivationObservationEventData | HarvestEventData | PackingEventData | PlantingEventData | SowingEventData | TableSpreadEventData | WastageEventData;
}
export interface EventOpt { 
    id?: string;
    batchId?: string;
    /**
     * Id of user who added this entry
     */
    userId?: string;
    /**
     * Time when the entry was added
     */
    startTime?: string;
    /**
     * Time when the entry was added
     */
    endTime?: string;
    type?: Event.TypeEnum;
    data?: CultivationObservationEventData | HarvestEventData | PackingEventData | PlantingEventData | SowingEventData | TableSpreadEventData | WastageEventData;
}
export namespace Event {
    export type TypeEnum = 'PLANTING' | 'SOWING' | 'PACKING' | 'TABLE_SPREAD' | 'CULTIVATION_OBSERVATION' | 'HARVEST' | 'WASTEAGE';
    export const TypeEnum = {
        PLANTING: 'PLANTING' as TypeEnum,
        SOWING: 'SOWING' as TypeEnum,
        PACKING: 'PACKING' as TypeEnum,
        TABLESPREAD: 'TABLE_SPREAD' as TypeEnum,
        CULTIVATIONOBSERVATION: 'CULTIVATION_OBSERVATION' as TypeEnum,
        HARVEST: 'HARVEST' as TypeEnum,
        WASTEAGE: 'WASTEAGE' as TypeEnum
    };
}
