/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EventType = 'PLANTING' | 'SOWING' | 'TABLE_SPREAD' | 'CULTIVATION_OBSERVATION' | 'HARVEST' | 'WASTAGE';

export const EventType = {
    PLANTING: 'PLANTING' as EventType,
    SOWING: 'SOWING' as EventType,
    TABLESPREAD: 'TABLE_SPREAD' as EventType,
    CULTIVATIONOBSERVATION: 'CULTIVATION_OBSERVATION' as EventType,
    HARVEST: 'HARVEST' as EventType,
    WASTAGE: 'WASTAGE' as EventType
};
