/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface HarvestEventData { 
    gutterCount?: number;
    type?: HarvestEventData.TypeEnum;
    /**
     * Production line id
     */
    productionLineId?: string;
}
export interface HarvestEventDataOpt { 
    gutterCount?: number;
    type?: HarvestEventData.TypeEnum;
    /**
     * Production line id
     */
    productionLineId?: string;
}
export namespace HarvestEventData {
    export type TypeEnum = 'BAGGING' | 'CUTTING' | 'BOXING';
    export const TypeEnum = {
        BAGGING: 'BAGGING' as TypeEnum,
        CUTTING: 'CUTTING' as TypeEnum,
        BOXING: 'BOXING' as TypeEnum
    };
}
