/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedValue } from './localizedValue';


export interface LocalizedEntry extends Array<LocalizedValue> { 
}
export interface LocalizedEntryOpt extends Array<LocalizedValue> { 
}
