/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PackingType = 'BASIC' | 'CAMPAIGN';

export const PackingType = {
    BASIC: 'BASIC' as PackingType,
    CAMPAIGN: 'CAMPAIGN' as PackingType
};
