/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PackingState } from './packingState';
import { PackingType } from './packingType';


export interface Packing { 
    id?: string;
    productId?: string;
    campaignId?: string;
    time: string;
    /**
     * Amount of created packages
     */
    packedCount?: number;
    packageSizeId?: string;
    state: PackingState;
    type: PackingType;
}
export interface PackingOpt { 
    id?: string;
    productId?: string;
    campaignId?: string;
    time?: string;
    /**
     * Amount of created packages
     */
    packedCount?: number;
    packageSizeId?: string;
    state?: PackingState;
    type?: PackingType;
}
