/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PackingState = 'IN_STORE' | 'REMOVED';

export const PackingState = {
    INSTORE: 'IN_STORE' as PackingState,
    REMOVED: 'REMOVED' as PackingState
};
