/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PackingEventData { 
    /**
     * Amount of packed items
     */
    packedAmount?: number;
    packageSizeId?: string;
}
export interface PackingEventDataOpt { 
    /**
     * Amount of packed items
     */
    packedAmount?: number;
    packageSizeId?: string;
}
