/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlantingEventData { 
    /**
     * Production line id
     */
    productionLineId?: string;
    gutterNumber?: number;
    /**
     * How many gutter were used during the planting
     */
    gutterCount?: number;
    /**
     * How many trays were planted
     */
    trayCount?: number;
    /**
     * How many workers were doing the planting
     */
    workerCount?: number;
}
export interface PlantingEventDataOpt { 
    /**
     * Production line id
     */
    productionLineId?: string;
    gutterNumber?: number;
    /**
     * How many gutter were used during the planting
     */
    gutterCount?: number;
    /**
     * How many trays were planted
     */
    trayCount?: number;
    /**
     * How many workers were doing the planting
     */
    workerCount?: number;
}
