/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PotType = 'SMALL' | 'LARGE';

export const PotType = {
    SMALL: 'SMALL' as PotType,
    LARGE: 'LARGE' as PotType
};
