/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedEntry } from './localizedEntry';


export interface Product { 
    id?: string;
    name?: LocalizedEntry;
    defaultPackageSizeId?: string;
    isSubcontractorProduct: boolean;
}
export interface ProductOpt { 
    id?: string;
    name?: LocalizedEntry;
    defaultPackageSizeId?: string;
    isSubcontractorProduct?: boolean;
}
