/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SeedBatch { 
    id?: string;
    /**
     * Manufacturer's code for the batch
     */
    code?: string;
    seedId?: string;
    /**
     * Time when the seed has arrived
     */
    time?: string;
}
export interface SeedBatchOpt { 
    id?: string;
    /**
     * Manufacturer's code for the batch
     */
    code?: string;
    seedId?: string;
    /**
     * Time when the seed has arrived
     */
    time?: string;
}
