/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Event of spreading the young plant trays to nursery tables
 */
export interface TableSpreadEventData { 
    /**
     * Count of trays used
     */
    trayCount?: number;
    /**
     * Where the batch has been placed
     */
    location?: string;
}
export interface TableSpreadEventDataOpt { 
    /**
     * Count of trays used
     */
    trayCount?: number;
    /**
     * Where the batch has been placed
     */
    location?: string;
}
