/**
 * Famifarm-API
 * Famifarm API specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventType } from './eventType';


/**
 * Entry of products has been thrown away
 */
export interface WastageEventData { 
    /**
     * Id of reason a product has been thrown away
     */
    reasonId: string;
    amount: number;
    productionLineId?: string;
    phase: EventType;
}
export interface WastageEventDataOpt { 
    /**
     * Id of reason a product has been thrown away
     */
    reasonId?: string;
    amount?: number;
    productionLineId?: string;
    phase?: EventType;
}
