export * from './batches.service';
import { BatchesService } from './batches.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './packageSizes.service';
import { PackageSizesService } from './packageSizes.service';
export * from './performedCultivationActions.service';
import { PerformedCultivationActionsService } from './performedCultivationActions.service';
export * from './productionLines.service';
import { ProductionLinesService } from './productionLines.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './seedBatches.service';
import { SeedBatchesService } from './seedBatches.service';
export * from './seeds.service';
import { SeedsService } from './seeds.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './wastageReasons.service';
import { WastageReasonsService } from './wastageReasons.service';
export const APIS = [BatchesService, EventsService, PackageSizesService, PerformedCultivationActionsService, ProductionLinesService, ProductsService, SeedBatchesService, SeedsService, TeamsService, WastageReasonsService];
